---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app-53-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-demo-video/my-quarkus-app-53-gitops